# You will probably want to edit this makefile to suit your needs better, for now, this is good enough
# Requirements: 64bit gcc, this makefile is for windows, 
all:
	C:/mingw64/bin/gcc -I "C:/Program Files/Java/jdk1.8.0_121/include" -I "C:/Program Files/Java/jdk1.8.0_121/include/win32" -Wl,--add-stdcall-alias -m64 -shared -o ../res/Operator.dll Operator.c