/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Operator */

#ifndef _Included_Operator
#define _Included_Operator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Operator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Operator_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Operator
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Operator_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Operator
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Operator_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Operator
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Operator_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Operator
 * Method:    mod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Operator_mod
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
